name       : haskell-dlist
version    : 0.8.0.2
release    : 2
source     :
    - https://hackage.haskell.org/package/dlist-0.8.0.2/dlist-0.8.0.2.tar.gz : 77397ecfb9a7cbfac15226cbe09ec156a3deb6e21c7af948bc8ab459e88641b1
license    : BSD-3-Clause
component  : programming.haskell
summary    : Difference lists are a list-like type supporting O(1) append
description: |
    Difference lists are a list-like type supporting O(1) append
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
