name       : haskell-dlist
version    : 0.8.0.7
release    : 5
source     :
    - https://hackage.haskell.org/package/dlist-0.8.0.7/dlist-0.8.0.7.tar.gz : a3c06a200f9756329b09d415e7733b7204dda76ce07783e6457d0ab9ffbcba2c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Difference lists are a list-like type supporting O(1) append
description: |
    Difference lists are a list-like type supporting O(1) append
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
