name       : haskell-dlist
version    : 0.8.0.2
release    : 1
source     :
    - https://hackage.haskell.org/package/dlist-0.8.0.2/dlist-0.8.0.2.tar.gz : 77397ecfb9a7cbfac15226cbe09ec156a3deb6e21c7af948bc8ab459e88641b1
license    : BSD-3-Clause
component  : programming
summary    : Difference lists are a list-like type supporting O(1) append
description: |
    Difference lists are a list-like type supporting O(1) append
builddeps  :
    - ghc
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --datadir=/usr/share \
                      --sysconfdir=/etc \
                      --libexecdir=/usr/lib64/cabal \
                      --libsubdir="\$compiler/\$pkgid"
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 dlist-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/dlist-$version.conf

